<div class="footer content hamburgermenu-ammachinery">
	<div class="open-menu">
		<div id="mobile-menu">
			<div class="row d-flex navlinks-cs header-links">
				<div class="widget-inner first-hum-section"><a href="https://ammachinery.nl"><img src="/pub/media/wysiwyg/logo_harvester-wit.png" alt=""></a>
					<div class="widget">
						<h3 class="widget-title">AM MACHINERY</h3>
						<div class="textwidget">
							<ul class="footer_link_address">
								<ul class="footer_link_address">
									<li class="white-clr">Veulenseweg 35<br>5814 AA Veulen<br>The Netherlands</li>
								</ul>
							</ul>
							<br>
							<ul class="footer_link_address">
								<li><a href="mailto:info@ammachinery.nl">info@ammachinery.nl</a></li>
								<li>T. <a href="tel:+31(0)478560016">+31 (0)478 56 00 16</a></li>
							</ul>
							<div class="">
								<ul class="social-icons">
									<li><a class="facebook" title="Facebook" href="https://www.facebook.com/ammachinery.nl/" target="_blank" rel="noopener"> <img class="" src="/pub/media/wysiwyg/fb_1.png" alt="Facebook"> Facebook </a></li>
									<li><a class="youtube" title="Follow on Youtube" href="https://www.youtube.com/channel/UCydFGahb1B9ZWC25LiR_g9Q" target="_blank" rel="noopener"> <img class="" src="/pub/media/wysiwyg/youtube_2.png" alt="YouTube"> YouTube </a></li>
									<li><a class="whatsapp" title="WhatsApp" href="#" target="_blank" rel="noopener"> <img class="" src="/pub/media/wysiwyg/whatsapp_1.png" alt="WhatsApp"> WhatsApp </a></li>
									<li><a class="wechat" title="WeChat" href="#" target="_blank" rel="noopener"> <img class="" src="/pub/media/wysiwyg/wechat_1.png" alt="WeChat"> WeChat </a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="widget-inner-right-section">
					<div class="widget-inner">
						<div class="widget">
							<h3 class="widget-title">SELF PROPPELLED FORAGE HARVESTERS</h3>
							<ul class="menu">
								<ul class="menu">
									<li><a href="#">stock SFPH</a></li>
									<li><a href="#">Stock John Deere SFPH</a></li>
									<li><a href="#">Stock Claas SFPH</a></li>
									<li><a href="#">Stock New Holland SFPH</a></li>
								</ul>
							</ul>
							<br>
							<ul class="menu">
								<li><a href="#">Landing SFPH1</a></li>
								<li><a href="#">Landing SFPH2</a></li>
								<li><a href="#">Landing SFPH3</a></li>
								<li><a href="#">Landing SFPH4</a></li>
								<li><a href="#">Landing SFPH4</a></li>
								<li><a href="#">Landing SFPH6</a></li>
							</ul>
						</div>
						<br><br><br>
						<div class="widget">
							<h3 class="widget-title">PARTS</h3>
							<ul class="menu">
								<ul class="menu">
									<li><a href="#">All Parts</a></li>
									<li><a href="#">Claas Parts</a></li>
									<li><a href="#">John Deere Parts</a></li>
									<li><a href="#">Kemper Parts</a></li>
								</ul>
							</ul>
							<br>
							<ul class="menu">
								<li><a href="#">Rockstopper</a></li>
								<li><a href="#">Landing parts 1</a></li>
								<li><a href="#">Landing parts 2</a></li>
							</ul>
						</div>
					</div>
					<div class="widget-inner">
						<div class="widget">
							<h3 class="widget-title">HARVESTER ATTACHMENTS</h3>
							<ul class="menu">
								<ul class="menu">
									<li><a href="#">All Attachments</a></li>
									<li><a href="#">Claas Attachments</a></li>
									<li><a href="#">John Deere Attachments</a></li>
									<li><a href="#">Kemper Attachments</a></li>
									<li><a href="#">New Holland Attachments</a></li>
								</ul>
							</ul>
							<br>
							<ul class="menu">
								<li><a href="#">Landing Attachments1</a></li>
								<li><a href="#">Landing Attachments1</a></li>
								<li><a href="#">Landing Attachments1</a></li>
								<li><a href="#">Landing Attachments1</a></li>
							</ul>
						</div>
						<br><br><br><br>
						<div class="widget">
							<h3 class="widget-title">TRACTORS</h3>
							<ul class="menu">
								<ul class="menu">
									<li><a href="#">All Tractors</a></li>
								</ul>
							</ul>
							<br>
							<ul class="menu">
								<li><a href="#">Landing Tractors1</a></li>
								<li><a href="#">Landing Tractors 2</a></li>
							</ul>
						</div>
					</div>
					<div class="widget-inner">
						<div class="widget">
							<h3 class="widget-title">CUSTOMER SERVICE AM MACHINERY</h3>
							<ul class="menu">
								<li><a href="#">About us</a></li>
								<li><a href="#">Contact</a></li>
								<li><a href="#">Bank Details</a></li>
								<li><a href="#">Metaalunie terms and conditions</a></li>
								<li><a href="#">Shipment &amp; transportation Rental &amp; financial lease</a></li>
								<li><a href="#">Workshop</a></li>
								<li><a href="#">Always on hand / regular stock</a></li>
								<li><a href="#">Satisfied customers around the globe</a></li>
								<li><a href="#">Privacy Policy</a></li>
								<li><a href="#">Terms and conditions</a></li>
								<li><a href="#">Jobs</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="cross-btn footer-hamburgermenu-close">&nbsp;</div>
		</div>
	</div>
</div>