
<!-- <div class="search_icon_custom" id="search_click_custom">    <a href="#" id="search_click_custom">Click Me</a>
</div> -->


<!-- 
<div id="popup-mpdal" >
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal'));
            $("#search_click_custom").on('click',function(){
                $("#popup-mpdal").modal("openModal");
            });

        }
    );
</script>
 -->