<?php if($this->isEnabled()){ ?>
<a  data-mage-init='{"PluginCompany_ProductPdf/js/link": <?php echo $this->getJsOptionsJSON(); ?>}'
    class="<?php echo $this->getLinkClasses();?> plugincompany productpdf pc-pdf-link print_pdf"
    href="<?php echo $this->getPdfUrl();?>"
    target="_blank"
    id="pc_pdf_link"
    >
    <i class="fas fa-print"></i> <?php echo $this->getLinkText();?></span>
    <?php }?>
</a>