<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Downloadable product links
 *
 * @var $block \Magento\Downloadable\Block\Catalog\Product\Samples
 */
?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
?>

<?php if ($customerSession->isLoggedIn()) : ?>
    <?php if ($block->hasSamples()) : ?>
        <dl class="items samples">
            <dt class="item-title samples-item-title">Downloads</dt>
            <?php $_samples = $block->getSamples() ?>
            <?php foreach ($_samples as $_sample) : ?>
                <dd class="item samples-item">
                    <a href="<?= $block->escapeHtml($block->getSampleUrl($_sample)) ?>" <?= $block->getIsOpenInNewWindow() ? 'onclick="this.target=\'_blank\'"' : '' ?>
                       class="item-link samples-item-link">
                        <?= $block->escapeHtml($_sample->getTitle()) ?>
                    </a>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php else:?>
        <span class="customaccountlink">
            Downloading a brochure? Please login with your account. No account yet? Create account&nbsp;
            <div class="button-wrapper"><a href="/customer/account/login">here >></a></div>
        </span>
<?php endif; ?>
