<?php 
$quickshopHelper = $this->helper('Emthemes\QuickShop\Helper\Data');
?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
	<div data-role="loader" class="loading-mask">
    	<div class="loader">
    		<img src="<?php  echo $block->getViewFileUrl('images/loader-1.gif'); ?>" alt="<?php  echo __('Loading...') ?>">
		</div>
    </div>
</div>
<?php 
/*Magnifier Option*/
if(!($magnifier_enabled = $quickshopHelper->getConfig('quickshop/magnifier_options/status')))$magnifier_enabled = $block->getVar("magnifier/enabled");
if(!($magnifier_fullscreenzoom = $quickshopHelper->getConfig('quickshop/magnifier_options/fullscreenzoom'))) 
    $magnifier_fullscreenzoom = $block->getVar("magnifier/fullscreenzoom");
if(!($magnifier_top = $quickshopHelper->getConfig('quickshop/magnifier_options/top'))) 
    $magnifier_top = $block->getVar("magnifier/top");
if(!($magnifier_left = $quickshopHelper->getConfig('quickshop/magnifier_options/left'))) 
    $magnifier_left = $block->getVar("magnifier/left");
if(!($magnifier_width = $quickshopHelper->getConfig('quickshop/magnifier_options/width'))) 
    $magnifier_width = $block->getVar("magnifier/width");
if(!($magnifier_height = $quickshopHelper->getConfig('quickshop/magnifier_options/height'))) 
    $magnifier_height = $block->getVar("magnifier/height");
if(!($magnifier_eventType = $quickshopHelper->getConfig('quickshop/magnifier_options/eventtype'))) 
    $magnifier_eventType = $block->getVar("magnifier/eventType");
?>
    <script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
        	"mage/gallery/gallery": {
        		"mixins":["magnifier/magnify"],
        		"magnifierOpts": {
                    <?php if ($magnifier_enabled): ?>
                        "enabled": <?php /* @escapeNotVerified */ echo $magnifier_enabled; ?>,
                    <?php endif; ?>
                   
                    "eventType": "<?php /* @escapeNotVerified */ echo $magnifier_eventType; ?>",
                
                
                    "width": "<?php /* @escapeNotVerified */ echo $magnifier_width; ?>",
               
                
                    "height": "<?php /* @escapeNotVerified */ echo $magnifier_height; ?>",
                
               
                    "top": "<?php /* @escapeNotVerified */ echo $magnifier_top; ?>",
                
               
                    "left": "<?php /* @escapeNotVerified */ echo $magnifier_left; ?>",
                
                
                    "fullscreenzoom": "<?php /* @escapeNotVerified */ echo $magnifier_fullscreenzoom; ?>"
                    
                },
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/nav") ?>",
                    <?php if (($block->getVar("gallery/loop"))): ?>
                        "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/loop") ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/keyboard"))): ?>
                        "keyboard": <?= /* @escapeNotVerified */ $block->getVar("gallery/keyboard") ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/arrows"))): ?>
                        "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/arrows") ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/allowfullscreen"))): ?>
                        "allowfullscreen": <?= /* @escapeNotVerified */ $block->getVar("gallery/allowfullscreen") ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/caption"))): ?>
                        "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/caption") ?>,
                    <?php endif; ?>
                    "width": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'width') ?>",
                    "thumbwidth": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_small', 'width') ?>",
                    <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
                        "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                        "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height')
                        ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/transition/effect") ?>",
                    <?php if (($block->getVar("gallery/navarrows"))): ?>
                        "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/navarrows") ?>,
                    <?php endif; ?>
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navtype") ?>",
                    "navdir": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navdir") ?>"
                },
                "fullscreen": {
                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/nav") ?>",
                    <?php if ($block->getVar("gallery/fullscreen/loop")): ?>
                        "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/loop") ?>,
                    <?php endif; ?>
                    "navdir": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navdir") ?>",
                    <?php if ($block->getVar("gallery/transition/navarrows")): ?>
                        "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navarrows") ?>,
                    <?php endif; ?>
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navtype") ?>",
                    <?php if ($block->getVar("gallery/fullscreen/arrows")): ?>
                        "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/arrows") ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/caption")): ?>
                        "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/caption") ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/effect") ?>"
                },
                "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>
            }
        }
    }
    </script>
        
       