    <?php   
/** 
 * Copyright © 2016 Magento. All rights reserved.   
 * See COPYING.txt for license details. 
 */ 
// @codingStandardsIgnoreFile   
/** @var $block \Magento\Catalog\Block\Product\View */  
?>  
<?php $_product = $block->getProduct(); ?>  
<?php $buttonTitle = __('Add to Cart'); ?>  
<?php if ($_product->isSaleable()): ?>  
<?php if($_product->getTypeId()!="downloadable") :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                <!-- ko template: getTemplate() --><!-- /ko -->
                <script type="text/x-magento-init">
                    {
                        "#custom-qty": {
                            "Magento_Ui/js/core/app": {
                                "components": {
                                    "qty-counter": {
                                        "component": "qty-counter",
                                        "config": {
                                            "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                            "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                        }
                                    }
                                 }
                            }
                        }
                    }
                </script>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
    <?php endif; ?> 
<?php endif; ?> 
<?php if ($block->isRedirectToCartEnabled()) : ?>   
<script type="text/x-magento-init"> 
    {   
        "#product_addtocart_form": {    
            "Magento_Catalog/product/view/validation": {    
                "radioCheckboxClosest": ".nested"   
            }   
        }   
    }   
</script>   
<?php else : ?> 
<script>    
    require([   
        'jquery',   
        'mage/mage',    
        'Magento_Catalog/product/view/validation',  
        'Emthemes_FlyingEffectCart/js/catalog-add-to-cart'  
    ], function ($) {   
        'use strict';   
        $('#product_addtocart_form').mage('validation', {   
            radioCheckboxClosest: '.nested',    
            submitHandler: function (form) {    
                var widget = $(form).catalogAddToCart({ 
                    bindSubmit: false   
                }); 
                widget.catalogAddToCart('submitForm', $(form)); 
                return false;   
            }   
        }); 
    }); 
</script>   
<?php endif; ?>