<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//g

    $categoryIds = $product->getCategoryIds();

    $categories = array(103,104,105,114,115,113,121,109,116,122,124,126,129,132,133,134,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,130,135,136,137,138,139,140,141,142,143,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,131,144,145,127,128,144,145,146,147,148,149,165,166,150,151,152,153,154,155,156,163,164,161,162,159,160,262,263,264,265,266,267,268,269,270,271,272,273,274,275);
    $flag = false;
    foreach ($categoryIds as $categoryId) {
        if (in_array($categoryId, $categories)) {
            $flag = true;
            break;
        }
    }

    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $newData = $product['hideonwebshop'];
    if(!$flag) { ?>
        <h3 class="col label text_machine1" scope="row"><?php echo __('Machine documents') ?></h3>
        <?php if($product->getTypeId()!="downloadable") :?>
            <?php if($this->isEnabled()){ ?>
                <a  data-mage-init='{"PluginCompany_ProductPdf/js/link": <?php echo $this->getJsOptionsJSON(); ?>}'
                    class="<?php echo $this->getLinkClasses();?> plugincompany productpdf pc-pdf-link"
                    href="<?php echo $this->getPdfUrl();?>"
                    target="_blank"
                    id="pc_pdf_link"
                    style="<?php echo $this->getLinkCss();?>" >

                    <?php if($this->displayIcon()){ ?>
                        <img title="<?php echo $this->getLinkText();?>"
                             alt="<?php echo $this->getLinkText(); ?>"
                             src="<?php echo $this->getIconUrl();?>"
                             style="<?php echo $this->getIconCss();?>" />
                    <?php } ?>
                    <?php if($this->displayLink()){ ?>
                        <div class="pdf_title"><span><?php //echo $this->getLinkText();?>AM </span>Machinery inspection certificate</div>
                    <?php }?>
                </a>
            <?php }  
        endif; 
    } 
?>

