<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;


if($_product->getWarrantyPackage()){ ?>
    <div class="warranty-package-custom">
        <?php 
        $warrantyvalue = $_product->getWarrantyPackage();
        if ($warrantyvalue == '7392') { ?>
            <div class="aewp"><img src="https://test.ammachinery.nl/media/wysiwyg/prodict-title-bej.png"><span>AM</span> Exclusive Warranty Package <span class="ques_tooltip">?</span></div>
            <div class="show_ewp"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('exclusive_warranty_package')->toHtml(); ?> </div>
       <?php }
        if ($warrantyvalue == '7391') { ?>
            <div class="aewp"><img src="https://test.ammachinery.nl/media/wysiwyg/prodict-title-bej.png"><span>AM</span> Premium Warranty package <span class="ques_tooltip">?</span></div>
            <div class="show_ewp"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('premium_warranty_package')->toHtml(); ?> </div>
       <?php }
        ?>
    </div>
<?php }

// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue) :?>
<div class="product attribute <?= $block->escapeHtmlAttr($_className) ?> <?php echo $_code; ?>">
    <?php if ($renderLabel) :?>
        <h3 class="col label" scope="row"><?= $block->escapeHtml($_attributeLabel) ?></h3>
    <?php endif; ?>
    <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div>
</div>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){ 
        jQuery('.aewp').on('click',function(){
           jQuery('.show_ewp').addClass('active');
        });
        jQuery('.cross-icon').on('click',function(){
           jQuery('.show_ewp').removeClass("active");
        });
    });   
</script>