<?php
$_product = $block->getProduct();
$productId = $_product->getId();
// if($_GET['myip'] == 123){
//   // echo $productId; exit();
// } 
$productImages = $block->getProductImages($productId);
$totalImageCount = count($productImages);
?>
<div class="more-views image-gallery-section" id="photos">
    <h3 class="image-title">
        <?php echo __('Image gallery'); ?>  
    </h3>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

        $customerSession = $objectManager->get('Magento\Customer\Model\Session');
        if($customerSession->isLoggedIn()) { ?>
        <ul id="photo-gallery">
        <?php $ct = 1; 
           foreach ($productImages as $_image): 
              if($ct <= $totalImageCount) {
        ?>
                <li>
                  <a href="<?php echo $_image->getUrl();?>" data-lightbox="image-1" data-title="These are pastel donuts"><img alt="Img Custom Gallery" class="img-custom-gallery" src="<?php echo $_image->getUrl();?>"></a>
                </li>
          <?php
              $ct++;
          }
          ?>
          <?php endforeach;?>
        </ul>
    <?php 
        if($totalImageCount ){ ?>
          <style type="text/css">
            .catalog-product-view .image-gallery-section {
                clear: both;
            }
          </style>
        <?php }
      }else{ ?>
        <ul id="photo-gallery">
        <?php $ct = 1; 
           foreach ($productImages as $_image): 
              if($ct <= 10) {
        ?>
                <li>
                  <a href="<?php echo $_image->getUrl();?>" data-lightbox="image-1" data-title="These are pastel donuts"><img alt="Img Custom Gallery" class="img-custom-gallery" src="<?php echo $_image->getUrl();?>"></a>
                </li>
          <?php
              $ct++;
          }
          ?>
          <?php endforeach;?>
        </ul>
        <?php
        
         if ($_product['hideonwebshop'] == "1")
         { 
          ?>  
            <div class="customer-login"><a href="<?php echo $this->getUrl('customer/account/login'); ?>">More images will be available after login</a></div>
          <?php
         } 
       } ?>
</div>
<script type="text/javascript">
require(['jquery',
], function ($) {
    $(document).ready(function () {
        $(document).on('click', '#our_producers_show_more_1', function () {
            var pid = "<?php echo $productId ?>";
            var baseUrl = "<?php echo $block->getBaseUrl() ?>";
            $.ajax({
                  url: "ajaxtest/index/index",
                  method: "POST",
                  data: {pid: pid},
                  dataType: "json",
                  showLoader: true,
                success: function (data)
                {
                    if(data){
                        var elements = '';
                        $(data).each(function(key, value){
                          elements += value;
                        });
                        $('#photo-gallery').append(elements);
                        $('#remove_row').hide();
                    }
                }
            });
        });
    });
});
</script>

<script type="text/javascript">
require(['jquery', 'lightbox'], function($, lightbox) {
});
</script>
