<div>
	<p class="buyinfo"><span class="deliverytitle"><?php echo __("Delivery packages:"); ?></span>
	<span class="inspectedimg"><img class='img-responsive' src='/media/Inspected-and-tested.png' /><span><?php echo __("inspected & tested "); ?></span></span>
	<span class="inspectedimg"><img class='img-responsive' src='/media/Inspecte-tested-and-parts.png' /><span> <?php echo __("inspected,tested & parts "); ?></span></span>
	<span class="inspectedimg"><img class='img-responsive' src='/media/Inspecte-tested-and-repaired.png' /><span> <?php echo __("inspected,tested & repaired"); ?> </span></span>
	<!-- <a href="#" class="readmore"> Read more >></a> -->
	</p>
</div>