<?php 
$_product = $block->getProduct();
$groupid=$block->getAttributeGroupId($_product->getAttributeSetId());
$attributesgroups=$block->getAttributeGroups($_product->getAttributeSetId());
$productAttributes=$_product->getAttributes();
$i=0;
$countAttributes=$block->getCountAttributes($_product,$attributesgroups,$productAttributes);
$type = $_product->getTypeId();


$categoryIds = $_product->getCategoryIds();

$categories = array(103,104,105,114,115,113,121,109,116,122,124,126,129,132,133,134,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,130,135,136,137,138,139,140,141,142,143,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,131,144,145,127,128,144,145,146,147,148,149,165,166,150,151,152,153,154,155,156,163,164,161,162,159,160,262,263,264,265,266,267,268,269,270,271,272,273,274,275);
$flag = false;
foreach ($categoryIds as $categoryId) {
    if (in_array($categoryId, $categories)) {
        $flag = true;
        break;
    }
}

?>
<div class="specification">
<?php
if($type!="downloadable") {
foreach ($attributesgroups as $attributesgroup):
    //print_r($attributesgroup->debug());
    // $attributes = $_product->getAttributes('attribute_group_id');
    if ($attributesgroup->getAttributeGroupCode() == 'tehnical-specifications' || $attributesgroup->getAttributeGroupCode() == 'options' || $attributesgroup->getAttributeGroupCode() == 'knive-drum' || $attributesgroup->getAttributeGroupCode() == 'kernal-processor') {
        $attributes = $block->getGroupAttributes($_product, $attributesgroup->getAttributeGroupId(), $productAttributes);

        $attGroup = $attributesgroup->getAttributeGroupCode();
        if ($attGroup == 'knive-drum' || $attGroup == 'kernal-processor') {
            if ($attGroup == 'knive-drum') { ?>
                <div class="technical-specification-content <?php echo $attGroup.'1'; ?>">
                     <ul>
                        <?php foreach ($attributes as $attribute): ?>
                            <?php $storelabel = $attribute->getStoreLabel();
                            if (trim($storelabel) == 'Type knife drum' || trim($storelabel) == 'Knife drum' || trim($storelabel) == 'Amount of knives installed') { ?>
                                <li>
                                <label class="label"><?php //echo $attribute->getFrontendLabel() ?>
                                    <?= $block->escapeHtml(__($attribute->getStoreLabel())) ?>
                                </label>
                                <span class="col data feature"><?php /* @escapeNotVerified */ echo $attribute->getFrontend()->getValue($_product) ?></span>
                            </li>
                            <?php }
                            ?>
                            
                        <?php endforeach;
                        ?>
                     </ul>
                </div> <?php
            } 
            if ($attGroup == 'kernal-processor') { ?>
                <div class="technical-specification-content <?php echo $attGroup.'1'; ?>">
                     <ul>
                        <?php foreach ($attributes as $attribute): ?>
                            <?php $storelabel = $attribute->getStoreLabel();
                            if (trim($storelabel) == 'Kernel processor type') { ?>
                                <li>
                                <label class="label"><?php //echo $attribute->getFrontendLabel() ?>
                                    <?= $block->escapeHtml(__($attribute->getStoreLabel())) ?>
                                </label>
                                <span class="col data feature"><?php /* @escapeNotVerified */ echo $attribute->getFrontend()->getValue($_product) ?></span>
                            </li>
                            <?php }
                            ?>
                            
                        <?php endforeach;
                        ?>
                     </ul>
                </div> <?php
            }
        }
        else { ?>
             <div class="technical-specification-wrapper">
            <?php if(!empty($attributes)){ ?>
                <h3 class="col label"><?php echo __($attributesgroup->getAttributeGroupName()); ?></h3>
            <?php } ?>
            <div class="technical-specification-content">
                     <ul>
                        <?php foreach ($attributes as $attribute): ?>
                            <li>
                                <label class="label"><?php //echo $attribute->getFrontendLabel();
                                    if ($flag && $attribute->getFrontendLabel() == "Stock Number") {
                                             echo __("Partnumber");
                                    }else{
                                        echo __($attribute->getFrontendLabel());
                                    }
                                 ?>
                                </label>
                                <span class="col data feature"><?php /* @escapeNotVerified */ echo $attribute->getFrontend()->getValue($_product) ?></span>
                            </li>
                        <?php endforeach;
                        ?>
                     </ul>
            </div>
        </div> <?php
        }
    }
    else {
        continue; 
    }
    endforeach; //die;
?>
<?php } ?>
</div>
<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
    $(document).ready( function() {
        if (screen.width >= 320 && screen.width <= 1199) {
             $('.technical-specification-wrapper h3.col.label').click(function(){
                $(this).toggleClass('expanded');
                $(this).siblings('.catalog-product-view .technical-specification-content').slideToggle();
            })
            $('.inspection-report-attr h3.col.label').click(function(){
                $(this).toggleClass('expanded');
                $(this).siblings('.catalog-product-view .inspection-report-row').slideToggle();
            })
            $('.product.attribute.overview h3.col.label').click(function(){
                $(this).toggleClass('expanded');
                $(this).siblings('.catalog-product-view .product.attribute.overview .value').slideToggle();
            })
        }
  });
});
</script>
<style type="text/css">
    .catalog-product-view .product-info-main .specification .technical-specification-wrapper:first-child {
        padding-bottom: 0;
    }
    /*.catalog-product-view .product-info-main .specification .knive-drum1 {
        margin-bottom: 15px;
    } */
</style>