<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;
            
            $image = 'related_products_list';
            $title = __('Other suggestions');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $isWeightedRandom = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;
            

            $image = 'upsell_products_list';
            $title = __('Available spare parts');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $isWeightedRandom = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'):?>
        <?php if ($type == 'related'):?>
<div class="block <?= $block->escapeHtmlAttr($class) ?> other-suggestions custom_suggestion"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
     data-shuffle="<?= /* @noEscape */ $shuffle ?>"
     data-shuffle-weighted="<?= /* @noEscape */ $isWeightedRandom ?>">
    <?php else:?>
    <div class="block <?= $block->escapeHtmlAttr($class) ?> available-spare-part"
         data-mage-init='{"upsellProducts":{}}'
         data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
         data-shuffle="<?= /* @noEscape */ $shuffle ?>"
         data-shuffle-weighted="<?= /* @noEscape */ $isWeightedRandom ?>">
        <?php endif; ?>
        <?php else:?>
        <div class="block <?= $block->escapeHtmlAttr($class) ?>">
            <?php endif; ?>
            
                <h3><?= $block->escapeHtml($title) ?></h3>
            
            <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart):?>
                    <!-- <div class="block-actions">
                        <?= $block->escapeHtml(__('Check items to add to the cart or')) ?>
                        <button type="button" class="action select"
                                data-role="select-all"><span><?= $block->escapeHtml(__('select all')) ?></span></button>
                    </div> -->
                <?php endif; ?>
                <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                    <?php if ($type == 'related'):?>
                    <ol class="products list items product-items owl-theme owl-carousel blog-slider" id="related-slider">
                    <?php else: ?>
                    <ol class="products list items product-items owl-theme owl-carousel blog-slider" id="upsell-slider">
                    <?php endif; ?>
                        <?php foreach ($items as $_item):?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'):?>
                                <?php if (!$_item->getRequiredOptions()):?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell'):?>
                                <li class="item product product-item"
                                id="product-item_<?= /* @noEscape */ $_item->getId() ?>"
                                data-shuffle-group="<?= $block->escapeHtmlAttr($_item->getPriority()) ?>" >
                                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                    'display:none;',
                                    'li#product-item_' . $_item->getId()
                                ) ?>
                            <?php else:?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @noEscape */ $available ?>">
                                <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php if ($type != 'related'):?>
                                        <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                    <?php endif; ?>
                                    <strong class="product name product-item-name"><a
                                                class="product-item-link"
                                                title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                                href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>
                                      
                                    <?php if ($type == 'related'):?>
                                        <ul class="products_attributes">
                                            <?php 
                                            //print_r(get_class_methods($_item->getRelatedProductCollection()->getProduct()));
                                            $sku = $_item->getRelatedProductCollection()->getProduct()->getSku();
                                            $counter1 = (double) ($_item->getRelatedProductCollection()->getProduct()->getResource()->getAttribute('counter1')->getFrontend()->getValue($_item->getRelatedProductCollection()->getProduct())) ?: '';
                                            $build_year = $_item->getRelatedProductCollection()->getProduct()->getAttributeText('build_year');
                                            
                                            $engineHp = (double) ($_item->getRelatedProductCollection()->getProduct()->getResource()->getAttribute('engine_power_hp')->getFrontend()->getValue($_item->getRelatedProductCollection()->getProduct())) ?: '';
                                            if (isset($sku) && !empty($sku)) {
                                                echo __("<li>".$block->escapeHtml(__('Stock Number: ')).$sku."</li>");
                                            }
                                            if (isset($build_year) && !empty($build_year)) {
                                                    echo __("<li><i class=\"far fa-calendar\"></i> ". $build_year."</li>");
                                                }
                                            if (isset($counter1) && !empty($counter1)) {
                                                echo __("<li class=\"clock-data\"><i class=\"fas fa-tachometer-alt\"></i> ". $counter1."</li>");
                                            }
                                            if (isset($engineHp) && !empty($engineHp)) { ?>
                                                <li class="engine-power_hp"><img src="<?php echo $block->getViewFileUrl('images/engine-icon.png'); ?>" alt="engine-power_hp"><?php echo $engineHp; ?></li>
                                            <?php } ?>
                                        </ul>
                                    <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                   <?php endif; ?>
                                    <?php if ($templateType):?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable()
                                        && $type == 'related'):?>
                                        <?php if (!$_item->getRequiredOptions()):?>
                                            <!-- <div class="field choice related">
                                                <input
                                                    type="checkbox"
                                                    class="checkbox related"
                                                    id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                                                    name="related_products[]"
                                                    value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                                <label class="label"
                                                       for="related-checkbox<?= $block->escapeHtmlAttr($_item->getId())
                                                        ?>"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </label>
                                            </div> -->
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($showAddTo || $showCart):?>
                                        <?php // phpcs:disable ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart):?>
                                                <div class="actions-primary">
                                                <?php if ($_item->isSaleable()):?>
                                                    <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)):?>
                                                        <button
                                                                class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else :?>
                                                        <?php
                                                        /** @var $viewModel PreparePostData */
                                                        $viewModel = $block->getViewModel();
                                                        $postArray = $viewModel->getPostData(
                                                            $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                            ['product' => $_item->getEntityId()]
                                                        );
                                                        $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                        ?>
                                                        <form data-role="tocart-form"
                                                              data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                              action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                              method="post">
                                                            <input type="hidden" name="product"
                                                                   value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>">
                                                            <input type="hidden"
                                                                   name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED?>"
                                                                   value="<?= /* @noEscape */ $value ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                    class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </form>
                                                    <?php endif; ?>
                                                <?php else:?>
                                                    <?php if ($_item->getIsSalable()):?>
                                                        <div class="stock available">
                                                            <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                        </div>
                                                    <?php else:?>
                                                        <div class="stock unavailable">
                                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showAddTo):?>
                                                <div class="secondary-addto-links actions-secondary"
                                                     data-role="add-to-links">
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                                        <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <?php // phpcs:enable ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
            <?php if ($type == 'related'):?>
                <div class="product-prgogressbar"><div class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                         </div><span class="slider__label"></span></div>
            <?php else: ?>
            <div class="product-prgogressbar"><div class="progress progress1" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                                </div><span class="slider__label"></span></div>
            <?php endif; ?>
        </div>
        
        
        <?php if (!$block->isRedirectToCartEnabled() && $_item):?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                    }
                }
            }
            </script>
        <?php endif;?>
        <?php endif;?>
<script type="text/javascript">
    require([
        'jquery',
        'owlcarousel'

    ], function($){
        $(document).ready(function() {
            $('#related-slider').owlCarousel({
                loop:false,
                nav:true,
                dots:false,
                autoplay:true,
                autoplayTimeout:3000,
                autoplayHoverPause: true,
                items: 4,
                autoWidth:false,
                // scrollbarType: "scroll",
                responsive: {
                    0: {
                        items: 1
                    },
                    480: {
                        items: 1
                    },
                    768: {
                        items: 3
                    },
                    991: {
                        items: 3
                    },
                    1024: {
                        items: 3
                    },
                    1199: {
                        items: 4
                    }
                }
            })
            var $relatedslider = $('.other-suggestions .blog-slider');
              var $relatedprogressBar = $('.other-suggestions .progress');
              var $relatedprogressBarLabel = $( '.other-suggestions .slider__label' );
              
              $relatedslider.on('changed.owl.carousel', function(event) {
                console.log(event);
                console.log(event.item.index, event.item.count);
                var relatedcalc = ( (event.item.index+event.page.size) / (event.item.count) ) * 100;
                console.log(relatedcalc);
                
                $relatedprogressBar
                  
                  .attr('aria-valuenow', relatedcalc );
                
                $relatedprogressBarLabel.css('background-size', relatedcalc + '% 100%');
              });
              $relatedslider.trigger('refresh.owl.carousel');
    });
});
</script>
<script type="text/javascript">
    require([
        'jquery',
        'owlcarousel'

    ], function($){
        $(document).ready(function() {
            $('#upsell-slider').owlCarousel({
                loop:false,
                nav:true,
                dots:false,
                autoplay:false,
                items: 4,
                autoWidth:false,
                slidesToShow: 4,
                slidesToScroll: 1,
                // scrollbarType: "scroll",
                responsive: {
                    0: {
                        items: 1
                    },
                    480: {
                        items: 1
                    },
                    768: {
                        items: 3
                    },
                    991: {
                        items: 3
                    },
                    1024: {
                        items: 3
                    },
                    1199: {
                        items: 4
                    }
                }
            })
            var $upsellslider = $('.upsell .blog-slider');
              var $upsellprogressBar = $('.upsell .progress');
              var $upsellprogressBarLabel = $( '.upsell .slider__label' );
              
              $upsellslider.on('changed.owl.carousel', function(event) {
                console.log(event);
                console.log(event.item.index, event.item.count);
                var upsellcalc = ( (event.item.index+event.page.size) / (event.item.count) ) * 100;
                console.log(upsellcalc);
                
                $upsellprogressBar
                  
                  .attr('aria-valuenow', upsellcalc );
                
                $upsellprogressBarLabel.css('background-size', upsellcalc + '% 100%');
              });
              $upsellslider.trigger('refresh.owl.carousel');


    });
});
</script>
<style type="text/css">
    .block.upsell.available-spare-part {padding: 60px 70px 0;}
    .block.related.custom_suggestion {padding: 30px 70px 0;}


@media(max-width: 1199px){
     .block.upsell.available-spare-part {padding: 60px 15px 0;}
    .block.related.custom_suggestion {padding: 30px 15px 0;}
}
</style>