<?php 
$product = $block->getProduct();
?>
<div class="product attribute overview custom_description">
        <div class="value" itemprop="description"><?php echo $product->getDescription(); ?></div>
</div>
<?php
if ($product['hideonwebshop'] == "0") 
{ 
    ?> 
        <div class="products_attributes replaces_oem">
            <?php
                if ( !empty($product['replaces_oem']) ) {
                    echo '<span class="replaces_oem_text">'.__("Replaces OEM : ").'</span><span class="replaces_oem_value">'.$product['replaces_oem'].'</span>';
                }
            ?>
        </div> 
    <?php
}


