<?php if($this->getGroupConfigFlag('additional_information/add_pagebreak')){ ?>
    <pagebreak />
<?php } ?>
<div class="section section-attributes attribute-options">
    <h3 class="section-title attributes-section-title">
        <?php echo __('Additional Information');?>
    </h3>
    <table autosize="1" class="product-options">
        <?php
        $i=0;
        foreach ($this->getAdditionalData() as $attribute) {
            $i++;
            ?>
            <tr class="<?php echo ($i % 2 === 0)? 'even': 'odd'; ?>">
                <td style="width:46%">
                    <?php echo __($attribute['label']); ?>
                </td>
                <td>
                    <?php if ($attribute['code'] == 'counter1') { // Cheat to get solution work
                        $value = preg_replace( '/[^0-9,"."]/', '', $attribute['value']);
                        if(substr($value,1,1) == '.'){
                            $value = strtok($value, ',');
                            $value = str_replace( '.', '', $value);
                        }
                        if(substr($value,1,1) == ','){
                            $value = strtok($value, '.');
                            $value = str_replace( ',', '', $value);
                        }
                        echo intval($value);
                    } else {
                       echo __($attribute['value']);
                    } ?>

                </td>
            </tr>
        <?php } ?>
    </table>
</div>
