<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php $total = $block->getItems()->getSize() ?>
<?php if ($total) :?>
    <a href="#" class="action print hidden-print" title="<?= $block->escapeHtmlAttr(__('Print This Page')) ?>">
        <span><?= $block->escapeHtml(__('Print This Page')) ?></span>
    </a>
        <div class="table-wrapper comparison 2121212">
            <table class="data table table-comparison" id="product-comparison"
                data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
                <caption class="table-caption"><?= $block->escapeHtml(__('Compare Products')) ?></caption>
                <thead>
                <tr>
                    <?php $index = 0 ?>
                    <?php foreach ($block->getItems() as $item) :?>
                        <?php if ($index++ == 0) :?>
                            <th scope="row" class="cell label remove"><span><?= $block->escapeHtml(__('Remove Product')) ?></span></th>
                        <?php endif; ?>
                        <td class="cell remove product hidden-print">
                            <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                            <a href="#" data-post='<?= /* @noEscape */ $compareHelper->getPostDataRemove($item) ?>'
                               class="action delete" title="<?= $block->escapeHtmlAttr(__('Remove Product')) ?>">
                                <span><?= $block->escapeHtml(__('Remove Product')) ?></span>
                            </a>
                        </td>
                    <?php endforeach; ?>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <?php $index = 0; ?>
                    <?php $helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
                    <?php /** @var $item \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($block->getItems() as $item) :?>
                        <?php if ($index++ == 0) :?>
                            <th scope="row" class="cell label product">
                                <span><?= $block->escapeHtml(__('Product')) ?></span>
                            </th>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Product')) ?>" class="cell product info">
                            <a class="product-item-photo"
                               href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                               title="<?= /* @noEscape */ $block->stripTags($item->getName(), null, true) ?>">
                                <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                            </a>
                            <strong class="product-item-name">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                   title="<?= /* @noEscape */ $block->stripTags($item->getName(), null, true) ?>">
                                    <?= /* @noEscape */ $helper->productAttribute($item, $item->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($item, 'short') ?>
                            <?= /* @noEscape */ $block->getProductPrice($item, '-compare-list-top') ?>
                            <div class="product-item-actions hidden-print">
                                <div class="actions-primary">
                                    <?php if ($item->isSaleable()) :?>
                                        <form data-role="tocart-form"
                                              action="<?= $block->escapeUrl($this->helper(Magento\Catalog\Helper\Product\Compare::class)->getAddToCartUrl($item)) ?>"
                                              method="post">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit" class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else :?>
                                        <?php if ($item->getIsSalable()) :?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else :?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow()) :?>
                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                        <a href="#"
                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($item) ?>'
                                           class="action towishlist"
                                           data-action="add-to-wishlist">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                        </a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </td>
                    <?php endforeach; ?>
                </tr>
                </tbody>
                <tbody>
                <?php foreach ($block->getAttributes() as $attribute) :?>
                    <?php $index = 0; 
                    $order = ['sku'=>1,'brand'=>2,'model'=>3,'year_of_manufacture_t'=>4,'series1'=>5,'counter1'=>6,'counter2'=>7,'attr_2_or_4_wheel_drive_t'=>8,'maximum_speed'=>9,'engine_power_hp'=>10,'engine_brand_t'=>11,'engine_type_t'=>12,'kernal_processor_type'=>13,'amount_knives_installed'=>14,'drum_type'=>15,'front_tyres_brand_t'=>16,'emission_level_t'=>17,'speedstar_t'=>18,'auto_lubrication_t'=>19,'rockstopper_t'=>20,'spout_extension_t'=>21,'automatic_spout_rotation_t'=>22,'autofill_t'=>23,'spout_camera_t'=>24,'rear_view_camera_t'=>25,'nir_sensor_t'=>26,'nir_sensor_cabling_t'=>27,'trailer_hitch_t'=>28,'dumpkit_t'=>29,'air_compressor_t'=>30,'tire_pressure_system_t'=>31,'innoculant_system_t'=>32,'innoculant_factory_installed_t'=>33,'Stocknumber_t'=>34,'brand_hpu'=>35,'model_hpu'=>36,'working_width_hpu'=>37,'autosteer_sensor_hcorn'=>38,'header_lateral_tilt_hcorn'=>39];
                    ?>
                    <?php if ($block->hasAttributeValueForProducts($attribute)) :?>
                         <tr data-position="<?php echo isset($order[$attribute->getAttributeCode()])?$order[$attribute->getAttributeCode()]:100; ?>">
                            <?php foreach ($block->getItems() as $item): ?>
                                <?php if ($index++ == 0) :?>
                                    <th scope="row" class="cell label">
                                        <span class="attribute label <?php echo $attribute->getAttributeCode(); ?>">
                                            <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                        </span>
                                    </th>
                                <?php endif; ?>
                                <td class="cell product attribute">
                                    <div class="attribute value">
                                        <?php switch ($attribute->getAttributeCode()) {
                                            case "price": ?>
                                                <?=
                                                /* @noEscape */ $block->getProductPrice(
                                                    $item,
                                                    '-compare-list-' . $attribute->getCode()
                                                )
                                                ?>
                                                <?php break;
                                            case "small_image": ?>
                                                <?php $block->getImage($item, 'product_small_image')->toHtml(); ?>
                                                <?php break;
                                            default :?>
                                                <?php if (is_string($block->getProductAttributeValue($item, $attribute))) :?>
                                                    <?= /* @noEscape */ $helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode()) ?>
                                                <?php else : ?>
                                                    <?=  $block->escapeHtml($helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode())) ?>
                                                <?php endif; 
                                            ?>
                                                <?php break;
                                        } ?>
                                    </div>
                                </td>
                            <?php endforeach; 
                            ?>
                        </tr>                        
                    <?php endif; ?>
                <?php endforeach; ?>              
                                    
                </tbody>
            </table>
        </div>
        <script>
            require(['jquery'], function ($) {
                console.log("12121212122222222222222222222222222222222");
                $("tbody").each(function() {
                    var $tbody = $(this);
                    var $rows = $tbody.children('tr');

                    console.log("Before sorting:");
                    $rows.each(function() {
                        console.log($(this).data('position'));
                    });

                    $rows.sort(function(a, b) {
                        var positionA = $(a).data('position');
                        var positionB = $(b).data('position');
                        return (positionA > positionB) ? 1 : (positionA < positionB) ? -1 : 0;
                    });

                    console.log("After sorting:");
                    $rows.each(function() {
                        console.log($(this).data('position'));
                    });

                    $tbody.append($rows);
                });
            });
        </script>
        <?php if (!$block->isRedirectToCartEnabled()) :?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>

        <?php endif; ?>
<?php else :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('You have no items to compare.')) ?></div></div>
<?php endif; ?>
