<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View\Addto\Compare */
?>
<a href="#" data-post='<?= /* @escapeNotVerified */ $block->getPostDataParams() ?>'
        data-role="add-to-links"
        class="action tocompare">
        <span><?= /* @escapeNotVerified */
                __('Compare') ?></span>
        </a>
<div id="elements"><input type="checkbox"  name="checkbox"  class="custom_checkbox_compare"></div>

<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
	$(document).ready( function() {
		$('#elements').click(function(){
			$('a.action.tocompare').trigger('click');
  		});
	});
});
</script>