<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

$blockObj           = $block->getLayout()->createBlock('Emizen\Restrictcountry\Block\Restrict');
$customerSession    = $blockObj->getSession();
$storeId            = $blockObj->getStoreId();
$countryCode        = $blockObj->getRestrictCountry(); 
$helper             = $this->helper('Mageplaza\GeoIP\Helper\Address');
$geoipData          = $helper->getGeoIpData($storeId);
$countryId          = $geoipData['country_id'];
$categories         = $blockObj->getCategorys();
$getGroupId         = $blockObj->getGroupId();
$flag = 0;
//echo "<pre>";

//print_r($categories);
//echo $getGroupId;
$hideonwebshop = 0;
if ($request->getFullActionName() == 'catalog_product_view') {
    $_product           = $blockObj->getCurrentProduct();
    $productId          = $_product->getId();
    $hideonwebshop      = $_product['hideonwebshop'];
    $getCatIdsByPid     = $blockObj->getCategoryIds($productId);
//print_r($getCatIdsByPid);
        $peopleContainsCriminal = array_intersect($getCatIdsByPid, $categories);
    if ($peopleContainsCriminal) {
        if (in_array($countryId, $countryCode)){

            if ($getGroupId != 4) {
                $flag = 1;
            }  
        }
    }
}

?>
<?php if ($flag || $hideonwebshop) :?>
    <span class="request-price"><?php echo __("Price on request");?>
    <style type="text/css">
        .product-add-form{
            display: none;
        }
    </style>
<?php else :?>
    <?php if ($block->hasSpecialPrice()) :?>
        <span class="special-price">
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
        <span class="old-price">
            <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
        <?php if ($request->getFullActionName() == 'catalog_product_view' || $request->getFullActionName() == 'catalog_category_view') : ?>
            <span  class="excl-tax-content"><?php echo __("VAT and transportation not included") ?></span>
        <?php endif; ?>
    <?php else :?>
        <?php if ($finalPriceModel->getAmount() == '0'): ?>
            <span class="request-price"><?php echo __("Price On Request");?>
        <?php else: ?>
            <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
            <?php if ($request->getFullActionName() == 'catalog_product_view' || $request->getFullActionName() == 'catalog_category_view') : ?>
                <span  class="excl-tax-content"><?php echo __("VAT and transportation not included") ?></span>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($block->showMinimalPrice()) :?>
        <?php if ($block->getUseLinkForAsLowAs()) :?>
            <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
                <?= /* @noEscape */ $block->renderAmountMinimal() ?>
            </a>
        <?php else :?>
            <span class="minimal-price-link">
                <?= /* @noEscape */ $block->renderAmountMinimal() ?>
            </span>
        <?php endif?>
        <?php if ($request->getFullActionName() == 'catalog_product_view' || $request->getFullActionName() == 'catalog_category_view') : ?>
            <span  class="excl-tax-content"><?php echo __("VAT and transportation not included") ?></span>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
